// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using xAzubiLog.Data;

#nullable disable

namespace xAzubiLog.Migrations
{
    [DbContext(typeof(xAzubiLog.Data.xAzubiLogContext))]
    partial class xAzubiLogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("xAzubiLog.Models.Ausbilder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abteilung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Ausbilder");
                });

            modelBuilder.Entity("xAzubiLog.Models.BerichtEintraege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auftragsnummer")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AusbilderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenutzerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Dauer")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Endzeit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fach")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeändertAm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notiz")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Startzeit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tagestyp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WochenberichtId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AusbilderId");

                    b.HasIndex("BenutzerId");

                    b.HasIndex("KategorieId");

                    b.HasIndex("WochenberichtId");

                    b.ToTable("BerichtEintraege");
                });

            modelBuilder.Entity("xAzubiLog.Models.Kategorie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenutzerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FarbeHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Reihenfolge")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("BenutzerId");

                    b.ToTable("Kategorie");
                });

            modelBuilder.Entity("xAzubiLog.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ausbildungsberuf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Klasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswortHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Schule")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("xAzubiLog.Models.Wochenbericht", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenutzerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<double>("Gesamtstunden")
                        .HasColumnType("REAL");

                    b.Property<int>("Jahr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kalenderwoche")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kommentar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BenutzerId");

                    b.ToTable("Wochenbericht");
                });

            modelBuilder.Entity("xAzubiLog.Models.BerichtEintraege", b =>
                {
                    b.HasOne("xAzubiLog.Models.Ausbilder", "Ausbilder")
                        .WithMany("BerichtEintraege")
                        .HasForeignKey("AusbilderId");

                    b.HasOne("xAzubiLog.Models.User", "Benutzer")
                        .WithMany("BerichtEintraege")
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("xAzubiLog.Models.Kategorie", "Kategorie")
                        .WithMany()
                        .HasForeignKey("KategorieId");

                    b.HasOne("xAzubiLog.Models.Wochenbericht", "Wochenbericht")
                        .WithMany("BerichtEintraege")
                        .HasForeignKey("WochenberichtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ausbilder");

                    b.Navigation("Benutzer");

                    b.Navigation("Kategorie");

                    b.Navigation("Wochenbericht");
                });

            modelBuilder.Entity("xAzubiLog.Models.Kategorie", b =>
                {
                    b.HasOne("xAzubiLog.Models.User", "Benutzer")
                        .WithMany("Kategorien")
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benutzer");
                });

            modelBuilder.Entity("xAzubiLog.Models.Wochenbericht", b =>
                {
                    b.HasOne("xAzubiLog.Models.User", "Benutzer")
                        .WithMany("Wochenberichte")
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benutzer");
                });

            modelBuilder.Entity("xAzubiLog.Models.Ausbilder", b =>
                {
                    b.Navigation("BerichtEintraege");
                });

            modelBuilder.Entity("xAzubiLog.Models.User", b =>
                {
                    b.Navigation("BerichtEintraege");

                    b.Navigation("Kategorien");

                    b.Navigation("Wochenberichte");
                });

            modelBuilder.Entity("xAzubiLog.Models.Wochenbericht", b =>
                {
                    b.Navigation("BerichtEintraege");
                });
#pragma warning restore 612, 618
        }
    }
}
